name: Deploy Docker to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: docker build -t flask-app .

    # Step 4: Save the Docker image
    - name: Save Docker Image as TAR
      run: docker save flask-app > flask-app.tar

    # Step 5: Copy the Docker image to Azure VM
    - name: SCP Docker Image to Azure VM
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.VM_PUBLIC_IP }}
        username: adminuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: flask-app.tar
        target: /home/adminuser/

    # Step 6: SSH into Azure VM and Deploy Docker
    - name: Deploy Docker Container
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VM_PUBLIC_IP }}
        username: adminuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker load < /home/adminuser/flask-app.tar
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d -p 80:80 --name flask-container flask-app
